### ISSUE TITLE
PyCharmでの起動時エラー

### ISSUE THREAD

**Issue by ykoga-kyutech** [koga-yatsushiro/one_month#58]
PyCharmで起動すると動かなくなった。コマンドプロンプト上では正常に動く。

C:\Users\tie304184\AppData\Local\Continuum\Miniconda3\python.exe C:/Users/tie304184/one_month/manage.py runserver 8000

Traceback (most recent call last):
  File "C:\Users\tie304184\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\apps\config.py", line 103, in create
    entry = module.default_app_config
AttributeError: 'module' object has no attribute 'default_app_config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/tie304184/one_month/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\tie304184\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "C:\Users\tie304184\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\core\management\__init__.py", line 312, in execute
    django.setup()
  File "C:\Users\tie304184\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\tie304184\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\tie304184\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\apps\config.py", line 106, in create
    return cls(entry, module)
  File "C:\Users\tie304184\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\apps\config.py", line 40, in __init__
    self.path = self._path_from_module(app_module)
  File "C:\Users\tie304184\AppData\Local\Continuum\Miniconda3\lib\site-packages\django\apps\config.py", line 69, in _path_from_module
    "with a 'path' class attribute." % (module, paths))
django.core.exceptions.ImproperlyConfigured: The app module <module 'accounts' (namespace)> has multiple filesystem locations (['C:\\Users\\tie304184\\one_month\\accounts', 'C:\\Users\\tie304184\\one_month\\accounts']); you must configure this app with an AppConfig subclass with a 'path' class attribute.

Process finished with exit code 1

**Comment by ykoga-kyutech** [comment]
【解決】
question/, accounts/, one_month/ に__init__.pyがなかったのが原因。
v1.0では存在していたのでに、なぜなくなったのかは不明。
